apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v04cvztpp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v04cvztpp-java-springboot-gitops